### ISSUE TITLE
allow-griefing: false doesn't work for ghasts

### ISSUE THREAD

**Issue by Impact009** [pl3xgaming/Purpur#1264]
### Spark link

https://spark.lucko.me/L471I4aT5b

### Expected behavior

Ghasts should not be able to destroy blocks.

### Observed/Actual behavior

Ghasts are able to destroy blocks.

### Steps/models to reproduce

/difficulty normal
/gamerule mobGriefing true

### Purpur version

_Checking version, please wait..._
Current: git-Purpur-1907 (MC: 1.19.3)*
Previous: git-Purpur-1905 (MC: 1.19.3)
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by RhythmicSys** [comment]
I was unable to reproduce this issue

To double check, did you do the gamerule command in the world that this issue is taking place in? Because of how bukkit handles worlds, gamerules are world specific

**Comment by Impact009** [comment]
Yes, I did. To verify, allow-griefing: false needs to go into purpur.yml, correct?

`      ghast:
        ridable: false
        ridable-in-water: false
        controllable: true
        ridable-max-y: 320.0
        allow-griefing: false
        attributes:
          max_health: 10.0
        takes-damage-from-water: false
        always-drop-exp: false`

I kept the default settings but had to add a new line for allow-griefing: false. It wasn't working on a fresh 1905 server either using Win11 Pro x64 and Corretto. I'll try reinstalling from scratch with 1907.

**Comment by RhythmicSys** [comment]
Newly generated config on the current build generated this 
```yml
ghast:
        ridable: false
        ridable-in-water: false
        controllable: true
        ridable-max-y: 320.0
        attributes:
          max_health: 10.0
        takes-damage-from-water: false
        always-drop-exp: false
```
Does not appear to have a `allow-griefing` option, many of the mobs have a `bypass-mob-griefing` option, but this doesn't appear to be one of them

Are there any errors in your console when purpur loads?
