### ISSUE TITLE
Silverfish bypass-mob-griefing doesn't work

### ISSUE THREAD

**Issue by bobhenl** [pl3xgaming/Purpur#1603]
### Spark link

https://spark.lucko.me/Q7WGKzp0gR

### Expected behavior

Hello, there's issue with bypass (inverting) the mobGriefing behavior for various mobs.

I tried setting this to SIlverFIsh:
```yml
bypass-mob-griefing: true
```
```yml
      silverfish:
        ridable: false
        ridable-in-water: true
        controllable: true
        attributes:
          scale: 1.0
          movement_speed: 0.25
          attack_damage: 1.0
          max_health: 8.0
        bypass-mob-griefing: true
        takes-damage-from-water: false
        always-drop-exp: false
```

and I believe it should "invert" -> bypass the current gamerule settings.

So when I have set mobGriefing gamerule to true:
![image](https://github.com/user-attachments/assets/847834e7-4620-4a07-933a-34651ac41d28)
then setting the `bypass-mob-griefing: true` should BLOCK the silverfish from infecting blocks & from breaking the infested ones.

### Observed/Actual behavior

I tested it with the mentioned settings, gamerule mobGriefing to true & bypass to true, as well, but the silverfish can still infest blocks & break the infested blocks.

### Steps/models to reproduce

1. /minecraft:gamerule mobGriefing true
2. Set the `bypass-mob-griefing: true` for Silverfish in Purpur config
3. Take infested stone bricks
![image](https://github.com/user-attachments/assets/0b8affc6-0d45-49fd-802e-f3453fa88a5f)
4. Spawn silverfish within them
![image](https://github.com/user-attachments/assets/5c193246-3d0e-47b9-934b-2feb1e099d6b)
5. Hit silverfish (the new one will be spawned & block will be destroyed
![image](https://github.com/user-attachments/assets/ff243a4c-4d05-4932-aeb0-8c72830fdf8f)

### Purpur version

[14:09:31 INFO]: Checking version, please wait...
[14:09:31 INFO]: Current Purpur Version: 1.21.1-2328-d49ca07 (MC: 1.21.1)*
* You are running the latest version
Previous: 1.21.1-2327-4b57bed (MC: 1.21.1)
The latest one
![image](https://github.com/user-attachments/assets/04f5405f-ccfa-4ba6-b1aa-01305740b76d)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.
