### ISSUE TITLE
Option to change wandering trader spawn chance to per player.

### ISSUE THREAD

**Issue by mibby** [pl3xgaming/Purpur#170]
Would it be possible to add an option to change wandering trader spawn chance to be per-player? To match per-player mob spawns in Paper & per-player pillager patrols. This would be to prevent only 1 player getting a wandering trader out of everyone online.

paper.yml
```
    wandering-trader:
      spawn-minute-length: 1200
      spawn-day-length: 24000
      spawn-chance-failure-increment: 25
      spawn-chance-min: 25
      spawn-chance-max: 75
```
