### ISSUE TITLE
(Suggestion) Add configurable option to make other doors act like Iron Doors

### ISSUE THREAD

**Issue by LichLord91** [pl3xgaming/Purpur#171]
Hey Billy,

As you know Iron doors are awesome because only players can open then via a redstone input (assuming you're not using  pressure plates only haha). 

However iron doors don't match every builds aesthetic and I'd be cool if we could find a way replicate that behavior over to the other doors. 

My request would be to add a feature that would either 

A) Create a item block tag state for doors that could be modified via /data modify block or /setblock , preferably some way a regular player could.
 Example tag :

`minecraft:spruce_door[facing=east,half=upper,hinge=right,open=false,powered=false,**deny-mob-use=true**,**deny-villager-use=true**]
`
```
doors:
    activate: false
     deny-mob-usage-block-tag: true
     deny-villager-usage-block-tag:true

```
B) add specific door types  in purpur config that can do this example:

```
doors:
   activate:false
   deny-mob-usage: true
   deny-villager-usage:true
   types: 
   - minecraft:spruce_door
   - etc
   - etc
```

C) combo of A and B but also be

```
doors:
   activate:false
---- below is individual door toggle editable via block tags
  deny-mob-usage-block-tag: true
  deny-villager-usage-block-tag:true
---below is blanket usage
   deny-mob-usage: true
   deny-villager-usage:true
       types: 
       - all
       or
       - minecraft:spruce_door
       - etc
       - etc
```
       
  These are just examples, not sure what's doable but C) would be cool A) would be my preference if  C) is not doable so we can control this per door instead of blanket usage for each type.

**Comment by LichLord91** [comment]
Awesome! so this is a all or nothing option correct?

**Comment by granny** [comment]
> Awesome! so this is a all or nothing option correct?

https://pl3xgaming.github.io/PurpurDocs/Configuration/#door. You add which wooden doors require redstone through a list e.g.

```yml
door:
  requires-redstone:
    - oak_door
    - jungle_door
```

It's handled on a per-world basis.
