### ISSUE TITLE
Deleted

### ISSUE THREAD

**Issue by jacklollz2** [pl3xgaming/Purpur#336]
The contents of this have been erased.

**Comment by BillyGalbreath** [comment]
You likely don't have the permissions to the say command.

I just tested with this:

```yaml
command-block-overrides: []
ignore-vanilla-permissions: false
aliases:
  icanhasbukkit:
  - version $1-
  bc:
  - say $$1-
  - tell $$1- $$2-
  - version $1-
```

and it worked fine

![image](https://user-images.githubusercontent.com/332527/118375378-e2306680-b586-11eb-9415-8aa24dd297a2.png)
