### ISSUE TITLE
Option does not take effect

### ISSUE THREAD

**Issue by Canary233** [pl3xgaming/Purpur#834]
### Expected behavior

    I set
  `sand:
        fix-duping: false`
in purpur.yml

### Observed/Actual behavior

But sand still cannot be copied, the same save works fine on vanilla

### Steps/models to reproduce

Save from https://www.bilibili.com/video/BV1VL4y1h7zE

### Purpur version

[14:15:01 INFO]: Checking version, please wait...
[14:15:04 INFO]: This server is running Purpur version git-Purpur-1492 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 29b24bc on HEAD)
[14:15:04 INFO]: You are running the latest version

### Agreements

- [x] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by emielderckx** [comment]
You also need to set allow-piston-duplication to true in paper.yml for duping to work

**Comment by Canary233** [comment]
> You also need to set allow-piston-duplication to true in paper.yml for duping to work

I re-tested and it still doesn't work.

**Comment by BillyGalbreath** [comment]
There is nothing wrong with the settings. You just don't have an understanding of the bug you are trying to exploit. It was fixed in various spots in the server, meaning you need to toggle various settings to undo these fixes.

paper.yml:
```yaml
settings:
  unsupported-settings:
    allow-piston-duplication: true
```

purpur.yml
```yaml
world-settings:
  default:
    blocks:
      end_portal:
        safe-teleporting: false
      sand:
        fix-duping: false
```

With these settings, your server is effectively broken and exposed to exploits (even more than just duping, so be careful).

I strongly advise against doing this, and recommend you provide sand and other dupable items using other means. Maybe put a spawner cage that spits out sand items. Or give players access to /give or creative mode.
