### ISSUE TITLE
Low tp and lag issue

### ISSUE THREAD

**Issue by JoshuaPHYT** [pl3xgaming/Purpur#887]
### Timings link

https://timings.aikar.co/?id=9c7814bb821a403fa87068d4779b74c1

### Description of issue

I dont know why our server tps is always around 15-10.. and i already did some optimize on the server

### Purpur version

[15:27:39 INFO]: Current: git-Purpur-1544 (MC: 1.18.1)*

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by Pantera07** [comment]
```
ticks-per:
    monster-spawns: 10
    animal-spawns: 400
    water-spawns: 40
    water-ambient-spawns: 20
    water-underground-creature-spawns: 40
    ambient-spawns: 80
   ```
Edit bukkit.yml
