### ISSUE TITLE
elytra.damage-multiplied-by-speed is not functioning

### ISSUE THREAD

**Issue by radiant-ai** [pl3xgaming/Purpur#929]
### Timings link

https://timings.aikar.co/?id=72021d80517c4b2d9c59fda0b8223e86

### Expected behavior

Elytra gets damaged by a lot when I fly at a high speed.

### Observed/Actual behavior

Elytra receives 1 damage per second.

### Steps/models to reproduce

Get a fresh purpur server. Configure the related section:
```
      elytra:
        damage-per-second: 1
        damage-multiplied-by-speed: 50.0
        ignore-unbreaking: false
        damage-per-boost:
          firework: 0
          trident: 0
```
- `/give Player elytra`
- `/tp Player 0 100000 0`
- Fly straight down
- Notice that elytra still receives 1 damage per second.

### Purpur version

```
[03:43:27 INFO]: Current: git-Purpur-1594 (MC: 1.18.2)*
Previous: git-Purpur-1593 (MC: 1.18.2)
* You are running the latest version
```

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.
